# Change these first
owner: kuflow # Your GitHub organization or username, where this repository lives
repo: kuflow-status # The name of this repository

sites:
  - name: App
    url: https://app.kuflow.com
    icon: https://raw.githubusercontent.com/kuflow/kuflow-status/master/assets/favicon.ico
    headers:
      - "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"
  - name: Rest API
    url: https://api.kuflow.com
    icon: https://raw.githubusercontent.com/kuflow/kuflow-status/master/assets/api-rest-icon.svg
    method: POST
    expectedStatusCodes:
      - 401
    headers:
      - "Authorization: Basic dummy"
      - "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"
  - name: Engine API
    check: "tcp-ping"
    url: engine.kuflow.com
    icon: https://raw.githubusercontent.com/kuflow/kuflow-status/master/assets/api-engine-icon.svg
    port: 443
    headers:
      - "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"

delay: 1000 # 1 seconds

assignees:
  - kuflow-devops

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kuflow.com
  # baseUrl: /
  logoUrl: https://raw.githubusercontent.com/kuflow/kuflow-status/master/assets/kuflow-icon.svg
  name: KuFlow
  introTitle: "**KuFlow services status**"
  introMessage: Status of **KuFlow** services in real time
  navbar:
    - title: Status
      href: /
    - title: KuFlow
      href: https://kuflow.com
    - title: GitHub
      href: https://github.com/$OWNER
  themeUrl: https://kuflow.github.io/kuflow-status/kuflow-theme.css
  favicon: https://kuflow.github.io/kuflow-status/favicon.ico
  faviconSvg: https://raw.githubusercontent.com/kuflow/kuflow-status/master/assets/kuflow-icon.svg

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
